### ISSUE TITLE
BCH pool asicboost compatibility

### ISSUE THREAD

**Issue by dh35** [ASICseer/asicseer-pool#1]
**Environment**
Devices: All asicboost compatible SHA256 miners

**Steps to Reproduce**
1. Have ASICseer ops connect asicboost compatible units to test pool
2. Verify asicboost compatibility and valid shares via pool and end-user miner 

**Expected Result**
Miner submits asicboost compatible shares to pool, pool accepts and processes them correctly, blocks are found (testnet, mainnet)

**Comment by cculianu** [comment]
Just to add info here: From my reading of the code it does use this version_mask scheme which I believe is what asicboost is expecting. Hopefully after testing we find out it works ok.

**Comment by dh35** [comment]
confirmed working
