### ISSUE TITLE
Change references from CKpool to asicseerpool

### ISSUE THREAD

**Issue by dh35** [ASICseer/asicseer-pool#14]
**Environment**
Github repo/all code

**Steps**
Remove all references to "ckpool" in the codebase and replace with "asicseerpool"

**Expected Result**
https://github.com/ASICseer/asicseer-pool/search?q=ckpool&unscoped_q=ckpool

The above link should return with zero results once completed

**Comment by cculianu** [comment]
Ok, no problem.  I can even rename the source files and the produced binaries to match the naming scheme.  It's  a bit long to type -- any chance you'd be ok with `aspool` or something similarly smaller?  If not for the main binary name, at least for the internal data structures?

So you want the binaries to be `asicseer*` I guess, then, right? (Or, maybe if I can convince you, `as*`.

So the produced binaries now are:

- `ckpool` <-- main pool app
- `ckmsg` <-- not sure what this does -- used in some configs
- `ckdb` <-- we don't use this right now and not sure if it plays nice with SPLNS anyway.
- `notifier`
- `summariser`

I could rename the above binaries that start with `ck` to:

- `asicseerpool`
- `asicseermsg`
- `asicseerdb`

Or maybe if you want to be compact:

- `aspool`
- `asmsg`
- `asdb`

.. and all associated build scripts, documentation, and internal data structure names.

Let me know what you think.

**Comment by cculianu** [comment]
Also the following would match the repo name:

```
asicseer-pool
asicseer-db
asicseer-msg
```

**Comment by cculianu** [comment]
This has now been addressed as discussed in #15
