### ISSUE TITLE
Hardcode coinbase scriptSig

### ISSUE THREAD

**Issue by ASICseer** [ASICseer/asicseer-pool#9]
**Environment**

coinbase scriptSig in found blocks.

**Feature Description**

Hard-code `pool.ASICseer.com`  as a _prefix_ and `BCHN` as the suffix for coinbase scriptSig. Customers who download and run our node can enter their own "middle" if they want. That way, its harder for them to change it.

**Steps to Reproduce**

Mine a block and check expected result:

**Expected Result**

Customers who run our open source pool software will signal:
  `pool.ASICseer.com BCHN`

Customers who edit the customizable portion to `mycustomsig` will end up with:
 `pool.ASICseer.com  mycustomsig BCHN`

**Comment by cculianu** [comment]
Fixed in latest commit
